### ISSUE TITLE
Add CRUD operation for "Product Category"

### ISSUE THREAD

**Issue by anantjain6** [anantjain6/ProductManagementSystem#11]
In admin panel add CRUD operation for "Product Category"

**Comment by naburigence** [comment]
Hi @anantjain6 , I would like to work on this

**Comment by anantjain6** [comment]
@naburigence Great! comment here in case you need any help

**Comment by naburigence** [comment]
@anantjain6 For Product Category, whether the CRUD operations to be added as separate tab named 'Product Category' like Products,Orders,etc., or inside the 'Category Report' Tab using action buttons

**Comment by anantjain6** [comment]
Please add separate tab as "Product Category" or "Category"

**Comment by anantjain6** [comment]
Closed by #35 

@naburigence Thanks for your contribution

Please star this repository if you like this project and watch this repository if you want to get updated with this repository

Cheers!
