### ISSUE TITLE
Set SMPT configuration through applicaion.prroperties

### ISSUE THREAD

**Issue by anantjain6** [anantjain6/ProductManagementSystem#12]
Current to set SMTP configuration, a person has to edit "EmailConfig" class file of "config" package.

Instead of it SMTP configuration should get set through `application.properties` file

**Comment by chinmay9194** [comment]
Hi,
I would like to work on this.

Can you please assign it to me?

Thanks

**Comment by Hitesh77** [comment]
Hi @anantjain6,

I have started working on this ticket.

Thanks

**Comment by chinmay9194** [comment]
Hi @Hitesh77,

I am already working on this.
Can you please checkout other issues in the list.

Thanks.

**Comment by Hitesh77** [comment]
Hi @chinmay919,

Sure, I will check out other issues.

Thanks

**Comment by anantjain6** [comment]
Closed by #15 

@chinmay9194 Thanks for your contribution

Please star this repository if you like this project and watch this repository if you want to get updated with updates to this repository

Cheers!

**Comment by chinmay9194** [comment]
@anantjain6 Yes sure, I liked the way the application is being built.
Due to your issue I was also able to learn the smtp configuration in Spring.

Cheers!

Thanks and Regards,
Chinmay
