### ISSUE TITLE
Handle Exceptions

### ISSUE THREAD

**Issue by anantjain6** [anantjain6/ProductManagementSystem#13]
Handle different exception such as product not found, order not found etc.

**Comment by kadariyaujwal** [comment]
Hello, I'd like to work in this one.

**Comment by anantjain6** [comment]
@kadariyaujwal Great! comment here in case you need any help

**Comment by ramgsuri** [comment]
Created a branch handle_exceptions, you will see a PR soon.

**Comment by ramgsuri** [comment]
Sure thanks

**Comment by anantjain6** [comment]
Closed by #20 

**@ramgsuri** Thanks for your contribution

Please star this repository if you like this project and watch this repository if you want to get updated with updates to this repository

Cheers!
