### ISSUE TITLE
Add javadoc comments

### ISSUE THREAD

**Issue by anantjain6** [anantjain6/ProductManagementSystem#2]
Add javadoc comments

**Comment by pavluchenko** [comment]
Hi, could you assign this issue to me? I want to work on this

**Comment by anantjain6** [comment]
@pavluchenko ,

Please directly make a pull request

**Comment by ramgsuri** [comment]
@anantjain6 raised PR for this one.

**Comment by anantjain6** [comment]
Closed by #19 

@ramgsuri Thanks for your contribution
