### ISSUE TITLE
Add Product filter by Category

### ISSUE THREAD

**Issue by anantjain6** [anantjain6/ProductManagementSystem#46]
In the customer Panel, add a new feature which will allow users to filter products based on one or more category

**Comment by fenix-hub** [comment]
Hi! I'd like to contribute to the repository implementing this functionality.
Hope you can assign this to me!

**Comment by anantjain6** [comment]
@fenix-hub You can work on this and create Pull Request

**Comment by fenix-hub** [comment]
PR #67 resolves this. Waiting for your review :)

**Comment by anantjain6** [comment]
Issue closed by PR #67
