### ISSUE TITLE
Adding french translation to the README.md

### ISSUE THREAD

**Issue by samcodesign** [anantjain6/ProductManagementSystem#52]

**Comment by STM3900** [comment]
Hello! I can help can you asign me on this?

**Comment by anantjain6** [comment]
Hi @STM3900 
Please directly submit the PR

**Comment by samcodesign** [comment]
Pull request sent I close the issue

**Comment by anantjain6** [comment]
Issue closed by PR #55

@samcodesign it is good practice to mention the PR number in the issue, or mention the issue number in the PR, this makes tracking easy ....
Anyways thanks for your contribution
