### ISSUE TITLE
Add License and Contributing.md file

### ISSUE THREAD

**Issue by PeritusDeveloper** [anantjain6/ProductManagementSystem#57]
## Proposed Changes

- Adding **Contributing.md** file will help the contributors to easily follow the instructions on forking ,adding files and making a PR.
- **LICENSE.md** should be added to **claim the work as your own.**

**Comment by ashiskumarnaik** [comment]
Hi @PeritusDeveloper can you assign me this issue under the label hactoberfest ?

**Comment by PeritusDeveloper** [comment]
I am not the owner of the repo @ashiskumarnaik
