### ISSUE TITLE
Add Timestamp (created & updated) to all model/entity

### ISSUE THREAD

**Issue by anantjain6** [anantjain6/ProductManagementSystem#61]
Add Timestamp (created & updated) to all model/entity

Task:
- In all Models/Entities add a property to store created and updated date/time
- Ad appropriate hibernate annotation to them
NOTE: Order model already has the property to store created time. Kindly make necessary changes for uniformity among the codebase.

**Comment by techrajdeep** [comment]
I am looking for an issue for my first contribution . Can you help me here. Can I take on this .

**Comment by anantjain6** [comment]
@techrajdeep yes, you can work in it
Read about "@CreationTimestamp" and "@UpdateTimestamp" annotation.
If you have other approaches to do this task then we can discuss that too.

**Comment by techrajdeep** [comment]
Hey @anantjain6  , Can we add below code for this?

@CreationTimestamp
@Temporal(TemporalType.TIMESTAMP)
@Column(name = "created_time")
private Date createdDate;

@UpdateTimestamp
@Temporal(TemporalType.TIMESTAMP)
@Column(name = "updated_time")
private Date updatedDate;

**Comment by anantjain6** [comment]
Closed by PR #70
