### ISSUE TITLE
Add Contributors in readme file

### ISSUE THREAD

**Issue by AnandSY** [anantjain6/ProductManagementSystem#64]
I want to make some changes in readme and add contributors to readme
please assign me this under hacktoberfest.

**Comment by anantjain6** [comment]
@AnandSY Thanks for suggestion of adding contributors in readme
But I don't think that purpose of ReadMe is for that.
Hence closing this issue.

**Comment by anantjain6** [comment]
Also, GitHub is already showing this info publically

![image](https://user-images.githubusercontent.com/22341750/194728225-5211ab8c-ae62-494e-9f55-ebace3950f23.png)
