### ISSUE TITLE
README.md update, adding CODE_of_CONDUCT.md and Contributing.md

### ISSUE THREAD

**Issue by Sowham-3098** [anantjain6/ProductManagementSystem#71]
* I want to add CODE_OF_CONDUCT.md , also want to add Contributing.md
* Want to update main README.md file with How To Contribute section and adding all contributors profiles into README.md

**Comment by Sowham-3098** [comment]
@anantjain6 Can I do this ?

**Comment by anantjain6** [comment]
@Sowham-3098 
Thanks for your suggestion
But we don't require CODE_OF_CONDUCT
Contribution Guidelines are already mentioned https://github.com/anantjain6/ProductManagementSystem#:~:text=Contribution%20Guildlines
Hence closing this issue

**Comment by anantjain6** [comment]
Also, GitHub is already showing contributors

![image](https://user-images.githubusercontent.com/22341750/194728225-5211ab8c-ae62-494e-9f55-ebace3950f23.png)
